//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;
using Encore.REST.Model.Entities;

/// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.17929")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class SerializationDocument
    {

        private object[] itemsField;

        /// <remarks/>
        [XmlElement("CreatedBy", typeof (Person))]
        [XmlElement("PrimaryArtist", typeof (PrimaryArtist))]
        [XmlElement("RequestedBy", typeof (Person))]
        [XmlElement("Track", typeof (Track))]
        [XmlElement("UpdatedBy", typeof (Person))]
        [XmlElement("element", typeof (Label))]
        public object[] Items
        {
            get { return this.itemsField; }
            set { this.itemsField = value; }
        }
    }
namespace Encore.REST.Model.Entities {
    
    
    public partial class NewDataSet {
    }
}
namespace Encore.REST.Model.Entities {
    
    
    public partial class NewDataSet {
    }
}
